# **Tayara Preprocessing**

Imports

In [9]:
import pandas as pd
import os

file_path = r"rawData/tayara_listings.csv"

if os.path.exists(file_path):
    df1 = pd.read_csv(file_path)
    print("File loaded, shape:", df1.shape)
else:
    print("File not found at:", os.path.abspath(file_path))
    
file_path = r"rawData/tayara_immobineuf_listings.csv"

if os.path.exists(file_path):
    df2 = pd.read_csv(file_path)
    print("File loaded, shape:", df2.shape)
else:
    print("File not found at:", os.path.abspath(file_path))
    
df = pd.concat([df1, df2], ignore_index=True)
print(" Tayar's raw data size ",len(df))
print("tayara's categories")
print(df['category'].unique())

File loaded, shape: (3000, 6)
File loaded, shape: (141, 6)
 Tayar's raw data size  3141
tayara's categories
['Terrains et Fermes' 'Maisons et Villas' 'Appartements'
 'Magasins, Commerces et Locaux industriels' 'Autres Immobiliers'
 'Bureaux et Plateaux' 'Immobilier Neuf']

In [10]:
df['neuf'] = df['category'] == "Immobilier Neuf"

In [11]:
df.head()

,url,title,price,location_time,category,seller,neuf
0,https://www.tayara.tn/item/terrains-et-fermes/...,Idéal pour habitation,NaN,"Kasserine, 8 minutes ago",Terrains et Fermes,NaN,False
1,https://www.tayara.tn/item/maisons-et-villas/b...,Hammam-Lif Chaabia villa 400 m² à vendre,NaN,"Ben Arous, 10 minutes ago",Maisons et Villas,NaN,False
2,https://www.tayara.tn/item/maisons-et-villas/b...,A VENDRE VILLA INDIVIDUELLE,NaN,"Ben Arous, 12 minutes ago",Maisons et Villas,NaN,False
3,https://www.tayara.tn/item/terrains-et-fermes/...,Soliman à vendre terrain 317m²,NaN,"Nabeul, 15 minutes ago",Terrains et Fermes,NaN,False
4,https://www.tayara.tn/item/maisons-et-villas/t...,VILLA D'EXCEPTION - HAUT STANDING À MENZEL AB...,NaN,"tunis, 16 minutes ago",Maisons et Villas,NaN,False

In [13]:
print(df.isnull().sum())

url                 0
title               0
price            3141
location_time       0
category            0
seller           3141
neuf                0
dtype: int64

# Les differentes catégories

In [14]:
df['category'].unique()

array(['Terrains et Fermes', 'Maisons et Villas', 'Appartements',
       'Magasins, Commerces et Locaux industriels', 'Autres Immobiliers',
       'Bureaux et Plateaux', 'Immobilier Neuf'], dtype=object)

Notre projet se focalise seulement sur les categories 'Maisons et Villas' , 'Appartements' et 'Immobilier Neuf'

In [16]:
df_clean=df[df.category.isin ( [ 'Maisons et Villas', 'Appartements','Immobilier Neuf'])].reset_index(drop=True)
len(df_clean)

2144

In [17]:
# Split location_time into location and time_ago

from datetime import datetime
import datetime as dt
import re
df=df_clean

df[['location', 'time_ago']] = df['location_time'].str.split(',', expand=True)
df['location'] = df['location'].str.strip()
df['time_ago'] = df['time_ago'].str.strip()

Ici on a l'attribut location represente la region

In [23]:
df['location'].unique()

array(['Ben Arous', 'tunis', 'Tunis', 'Monastir', 'Ariana', 'La Manouba',
       'Nabeul', 'Sousse', 'ariana', 'Médenine', 'sousse', 'Sfax',
       'Mahdia', 'Bizerte', 'Gabès', 'Béja', 'nabeul', 'sfax', 'Siliana',
       'Sidi Bouzid', 'la-manouba', 'ben-arous', 'Kasserine', 'Jendouba',
       'Gafsa', 'mahdia'], dtype=object)

Selection des colonnes

In [31]:
df['id']=df.index
df=df.rename(columns={
    'url': 'url',
    'title': 'titre',
    'price': 'prix',
    'location_time': 'location_time',
    'category': 'categorie',
    'seller': 'seller',
    'location': 'gouvernorat',
    'time_ago': 'published_on'
})

In [32]:
df.head()

,url,titre,prix,location_time,categorie,seller,neuf,gouvernorat,published_on,id
0,https://www.tayara.tn/item/maisons-et-villas/b...,Hammam-Lif Chaabia villa 400 m² à vendre,NaN,"Ben Arous, 10 minutes ago",Maisons et Villas,NaN,False,Ben Arous,10 minutes ago,0
1,https://www.tayara.tn/item/maisons-et-villas/b...,A VENDRE VILLA INDIVIDUELLE,NaN,"Ben Arous, 12 minutes ago",Maisons et Villas,NaN,False,Ben Arous,12 minutes ago,1
2,https://www.tayara.tn/item/maisons-et-villas/t...,VILLA D'EXCEPTION - HAUT STANDING À MENZEL AB...,NaN,"tunis, 16 minutes ago",Maisons et Villas,NaN,False,tunis,16 minutes ago,2
3,https://www.tayara.tn/item/appartements/ben-ar...,Appartement S+2 à El Médina Jadida,NaN,"Ben Arous, 16 minutes ago",Appartements,NaN,False,Ben Arous,16 minutes ago,3
4,https://www.tayara.tn/item/appartements/tunis/...,Appartement Ain_Zaghouan_sud,NaN,"Tunis, 23 minutes ago",Appartements,NaN,False,Tunis,23 minutes ago,4

In [33]:
df.columns

Index(['url', 'titre', 'prix', 'location_time', 'categorie', 'seller', 'neuf',
       'gouvernorat', 'published_on', 'id'],
      dtype='object')

In [34]:
#colonnes à considerer 
cols=["id","url","titre","categorie","gouvernorat",'neuf']
df=df[cols]

In [36]:
df["source"]="tayara"
df.head()

,id,url,titre,categorie,gouvernorat,neuf,source
0,0,https://www.tayara.tn/item/maisons-et-villas/b...,Hammam-Lif Chaabia villa 400 m² à vendre,Maisons et Villas,Ben Arous,False,tayara
1,1,https://www.tayara.tn/item/maisons-et-villas/b...,A VENDRE VILLA INDIVIDUELLE,Maisons et Villas,Ben Arous,False,tayara
2,2,https://www.tayara.tn/item/maisons-et-villas/t...,VILLA D'EXCEPTION - HAUT STANDING À MENZEL AB...,Maisons et Villas,tunis,False,tayara
3,3,https://www.tayara.tn/item/appartements/ben-ar...,Appartement S+2 à El Médina Jadida,Appartements,Ben Arous,False,tayara
4,4,https://www.tayara.tn/item/appartements/tunis/...,Appartement Ain_Zaghouan_sud,Appartements,Tunis,False,tayara

In [37]:
file_path = r"clean_rawData/clean_tayara_listings.csv"
df.to_csv(file_path)